// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[id]" | "/[id]/[discussion]" | "/settings"
type AppRouteHandlerRoutes = "/admin/imports/[jobId]" | "/admin/imports/[jobId]/retry-failed" | "/admin/imports/basecamp2" | "/auth/google/callback" | "/clients" | "/projects" | "/projects/[id]" | "/projects/[id]/archive" | "/projects/[id]/files" | "/projects/[id]/files/[fileId]/download-link" | "/projects/[id]/files/upload-complete" | "/projects/[id]/files/upload-init" | "/projects/[id]/restore" | "/projects/[id]/threads" | "/projects/[id]/threads/[threadId]" | "/projects/[id]/threads/[threadId]/comments" | "/projects/[id]/threads/[threadId]/comments/[commentId]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[id]": { "id": string; }
  "/[id]/[discussion]": { "id": string; "discussion": string; }
  "/admin/imports/[jobId]": { "jobId": string; }
  "/admin/imports/[jobId]/retry-failed": { "jobId": string; }
  "/admin/imports/basecamp2": {}
  "/auth/google/callback": {}
  "/clients": {}
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/projects/[id]/archive": { "id": string; }
  "/projects/[id]/files": { "id": string; }
  "/projects/[id]/files/[fileId]/download-link": { "id": string; "fileId": string; }
  "/projects/[id]/files/upload-complete": { "id": string; }
  "/projects/[id]/files/upload-init": { "id": string; }
  "/projects/[id]/restore": { "id": string; }
  "/projects/[id]/threads": { "id": string; }
  "/projects/[id]/threads/[threadId]": { "id": string; "threadId": string; }
  "/projects/[id]/threads/[threadId]/comments": { "id": string; "threadId": string; }
  "/projects/[id]/threads/[threadId]/comments/[commentId]": { "id": string; "threadId": string; "commentId": string; }
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
