// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[id]/[discussion]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[id]/[discussion]">> = Specific
  const handler = {} as typeof import("../../app/[id]/[discussion]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[id]">> = Specific
  const handler = {} as typeof import("../../app/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/imports/[jobId]/retry-failed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/imports/[jobId]/retry-failed">> = Specific
  const handler = {} as typeof import("../../app/admin/imports/[jobId]/retry-failed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/imports/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/imports/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/admin/imports/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/imports/basecamp2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/imports/basecamp2">> = Specific
  const handler = {} as typeof import("../../app/admin/imports/basecamp2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/google/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/clients">> = Specific
  const handler = {} as typeof import("../../app/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/archive">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/files/[fileId]/download-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/files/[fileId]/download-link">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/files/[fileId]/download-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/files">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/files/upload-complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/files/upload-complete">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/files/upload-complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/files/upload-init/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/files/upload-init">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/files/upload-init/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/restore">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/threads/[threadId]/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/threads/[threadId]/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/threads/[threadId]/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/threads/[threadId]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/threads/[threadId]/comments">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/threads/[threadId]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/threads/[threadId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/threads/[threadId]">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/threads/[threadId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[id]/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects/[id]/threads">> = Specific
  const handler = {} as typeof import("../../app/projects/[id]/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
